ALTER SESSION SET "_ORACLE_SCRIPT"=true;
DROP USER NETRUNNER CASCADE;
CREATE USER NETRUNNER IDENTIFIED BY "TASTY33"
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";
ALTER USER NETRUNNER QUOTA UNLIMITED ON USERS;
GRANT CREATE SESSION TO NETRUNNER;
GRANT "RESOURCE" TO NETRUNNER;
ALTER USER NETRUNNER DEFAULT ROLE "RESOURCE";